language: generic
before_install:
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y octave

dist: trusty

script: octave --no-gui --eval "addpath tests; RunAllTests;"
